# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    - pull_request

name: "Mutations testing"

jobs:
    run:
        name: "CI"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.0']

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - name: Install PHP
              uses: shivammathur/setup-php@2.30.0
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring,pcov

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v3.0.11
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run Grumphp
              run: vendor/bin/grumphp run --tasks=infection -n

            - name: Send feedback on Github
              if: ${{ failure() }}
              run: |
                vendor/bin/infection -j2 --logger-github
